/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "rdmsgtihqnpsobipnina"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJkbXNndGlocW5wc29iaXBuaW5hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA1NTY4ODQsImV4cCI6MjA3NjEzMjg4NH0.6V2i5kFTKWHjiWC7XhgK6EDu7g9xIMdY2awW-z1-Kog"